---
kind: pipeline
type: kubernetes
name: default

environment:
  URL: https://stable.release.flatcar-linux.net/amd64-usr
  VER: 2512.2.0
  IMAGE: flatcar_production_openstack_image.img
  IMAGE_Z: flatcar_production_openstack_image.img.bz2

steps:
- name: downloader
  image: einfachnuralex/downloader:v0.5
  commands:
  - wget -q $URL/$VER/$IMAGE_Z
  - wget -q $URL/$VER/$IMAGE_Z.DIGESTS
- name: checker
  image: einfachnuralex/downloader:v0.5
  commands:
  - sha512sum -c $IMAGE_Z.DIGESTS
- name: extractor
  image: einfachnuralex/downloader:v0.5
  commands:
  - bzip2 -df IMAGE_Z
  - ls -la
- name: uploader
  image: einfachnuralex/downloader:v0.5
  commands:
  - openstack image create coreos-$VER-test --disk-format=qcow2 --file IMAGE --public --property os_distro='coreos' --property os_type='linux'
  - echo done
  environment:
    OS_AUTH_URL:
      from_secret: authurl
    OS_PROJECT_ID:
      from_secret: projectid
    OS_PROJECT_NAME:
      from_secret: projectname
    OS_USER_DOMAIN_NAME:
      from_secret: domain
    OS_PROJECT_DOMAIN_ID:
      from_secret: domain
    OS_USERNAME:
      from_secret: username
    OS_PASSWORD:
      from_secret: password
    OS_REGION_NAME:
      from_secret: region
    OS_INTERFACE: public
    OS_IDENTITY_API_VERSION: 3
---
kind: secret
name: username
get:
  path: credentials
  name: username
---
kind: secret
name: password
get:
  path: credentials
  name: password
---
kind: secret
name: projectname
get:
  path: credentials
  name: projectname
---
kind: secret
name: projectid
get:
  path: credentials
  name: projectid
---
kind: secret
name: authurl
get:
  path: credentials
  name: authurl
---
kind: secret
name: domain
get:
  path: credentials
  name: domain
---
kind: secret
name: region
get:
  path: credentials
  name: region
